language: node_js
node_js:
  - "6"
sudo: required
dist: trusty
env:
  - NODE_ENV=PROD
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation ruby-full
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - eval "$(ssh-agent -s)"
  - openssl aes-256-cbc -K $encrypted_f2baaaee3923_key -iv $encrypted_f2baaaee3923_iv -in publish-key.enc -out publish-key -d
  - chmod 600 publish-key
  - ssh-add publish-key
install:
  - npm install
  - npm update
# script:
#   - jdk_switcher use oraclejdk8
#   - npm run test
notifications:
  email: false
script:
  - npm run test && node check_version.js
  - npm run openstudio-build && sed -i 's/\/static/static/g' dist/index.html && cp favicon.ico dist/
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
  on:
    branch: develop
